import triggerArray from './accordion.js'
import donate_container from './search.js'
import toggle_search2 from './search-mobile.js'
import mobile_nav from './menu.js'
import preLoader from './pre-loader.js'
import form from './form.js'